### ISSUE TITLE
4.2.* compatible?

### ISSUE THREAD

**Issue by palokankare** [clarification/sparkpost-laravel-driver#1]
Hi,

is this package 4.2 compatible?

**Comment by Lidbetter** [comment]
I have not tested it with 4.2

It should be - the container has not changed.

The read me instructions might not exactly line up - but should hopefully be obvious where config options should be put for 4.2

**Comment by Lidbetter** [comment]
No, I have fixed the minimum requirements to better indicate so.

If you would like to make it compatible, feel free to submit a PR
