### ISSUE TITLE
Sparkpost not working with laravel 5.4

### ISSUE THREAD

**Issue by taslimsuman** [clarification/sparkpost-laravel-driver#10]
I tried all steps but still getting error. Does it support 5.4? I got this error:
Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required
"

**Comment by Lidbetter** [comment]
Sounds like a configuration typo.

This package is not needed for Laravel 5.4, see end of readme: https://github.com/clarification/sparkpost-laravel-driver/tree/1.2.3

Here is the code which prevents this transport from loading if your version of Laravel already has a spark post driver:
https://github.com/clarification/sparkpost-laravel-driver/blob/1.2.3/src/SparkpostServiceProvider.php#L36

Here is the directory from the latest release (at the time of this comment) which shows the spark post transport included with the framework:
https://github.com/laravel/framework/tree/v5.4.21/src/Illuminate/Mail/Transport
