### ISSUE TITLE
Similar package

### ISSUE THREAD

**Issue by robsontenorio** [clarification/sparkpost-laravel-driver#15]
Hi,

What different between this packages? It seems does exactly same thing and with same configurations options.

https://github.com/vemcogroup/laravel-sparkpost-driver/issues/9

**Comment by Lidbetter** [comment]
Hi @robsontenorio 

Probably not much.

I do not currently work on any projects which use spark post, improvements/fixes have all been contributed by others. This package supports older versions of Laravel

Either would likely suit your needs, but if you are using latest version of laravel [vemcogroup/laravel-sparkpost-driver](https://github.com/vemcogroup/laravel-sparkpost-driver) is advertised as working and may be a better choice
