### ISSUE TITLE
Upgrading to Laravel 7.x: Unsupported mail transport [sparkpost].

### ISSUE THREAD

**Issue by realtebo** [clarification/sparkpost-laravel-driver#16]
I required your package

    "clarification/sparkpost-laravel-driver": "^1.2",

In `config\app.php`  I added provider to `providers` array

     'providers' => [
          ....
          Clarification\MailDrivers\Sparkpost\SparkpostServiceProvider::class,
          ....
     ]

My `.env` has

    MAIL_DRIVER=sparkpost

and `config\mail.php`  has

     'driver' => env('MAIL_DRIVER', 'smtp'),

I added to `config\services.php` 

    'sparkpost' => [
        'secret' => env('SPARKPOST_SECRET'),
        'options' =>  [
            'endpoint' => env('SPARKPOST_ENDPOINT'),
        ]
    ],

Problem
-

Sending a mail, I got

> InvalidArgumentException
> Unsupported mail transport [sparkpost].

**Comment by murtazasultani** [comment]
I fixed the issue using this package
https://github.com/vemcogroup/laravel-sparkpost-driver

**Comment by Lidbetter** [comment]
Thanks @murtazasultani for providing a more up to date alternative.

**Comment by Lidbetter** [comment]
This package is now marked as abandoned on packagist and will suggest:
https://github.com/vemcogroup/laravel-sparkpost-driver
